[package]
name = "oracle"
version = "0.0.1"
published-at = "0xc2d49bf5e75d2258ee5563efa527feb6155de7ac6f6bf025a23ee88cd12d5a83"

[dependencies.SupraOracle]
git = "https://github.com/Typus-Lab/dora-interface.git"
subdir = "sui/mainnet/supra_holder"
rev = "master"

[dependencies.Pyth]
git = "https://github.com/Typus-Lab/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "main"

[addresses]
oracle = "0xca441b44943c16be0e6e23c5a955bb971537ea3289ae8016fbf33fffe1fd210f"
